### ISSUE TITLE
feat: django rest framework setup

### ISSUE THREAD

**Issue by Blankscreen-exe** [lkuessner/patreon-clone-api#2]
Follow the documentation in the DRF official site and implement the latest DRF within the project

## Additional information

It is okay to review from some other sources as well but official docs would be preferred. If you review from other sources be sure to inform me about those sources.

**Comment by leku-codes** [comment]
Is there a link to the documentation?

Please be descriptive even if you and @PredaDavid talked about the issue in person so others can understand what this issue is about.

**Comment by PredaDavid** [comment]
Here is the documentation: https://www.django-rest-framework.org/
